CREATE TABLE usuario(
 Id_usuario INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 Nombre VARCHAR(50) NOT NULL,
 Apellido VARCHAR(50) NOT NULL,
 Nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
 Token VARCHAR(50) NOT NULL UNIQUE,
 Contraseña VARCHAR(50) NOT NULL,
 Ciudad VARCHAR(50) NOT NULL,
 Sexo VARCHAR(25) NOT NULL,
 Estado_civil VARCHAR(25) NOT NULL,
 Tipo_empresa VARCHAR(25) NOT NULL,     #cambiar a boolean
 Dirreccion VARCHAR(100) NOT NULL
);

CREATE TABLE autenticacion(
 Id_autenticacion INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 Nombre_usuario VARCHAR(50) NOT NULL,
 Contraseña VARCHAR(50) NOT NULL,
 Agente_usuario VARCHAR(50) NOT NULL,
 Token VARCHAR(50) NOT NULL,
 Tipo_usuario VARCHAR(50) NOT NULL,
 Fecha_hora DATETIME NOT NULL,
 FOREIGN KEY (Nombre_usuario) REFERENCES usuario(Nombre_usuario),
 FOREIGN KEY (Token) REFERENCES usuario(Token)
);

CREATE TABLE prueba(
 Id_prueba INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 Referencias VARCHAR(50) NOT NULL,
 Nombre VARCHAR(50) NOT NULL,
 Descripciom VARCHAR(50) NOT NULL,
 Fecha_ingreso DATETIME NOT NULL,
 Activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pago (
 Id_pago INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
Numero_tarjeta VARCHAR(50) NOT NULL,
Tarjeta_nombre VARCHAR(50) NOT NULL,
CVV INT NOT NULL,
Expiracion VARCHAR(10) NOT NULL,
Nombre_usuario VARCHAR(50) NOT NULL,
Tipo_tarjeta VARCHAR(20) NOT NULL,
FOREIGN KEY (Nombre_usuario) REFERENCES usuario (Nombre_usuario)
); 

